apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-concepts
  namespace: argocd 
spec: 
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: nodejs-concepts
  source:
    path: apps/nodejs-concepts
    targetRevision: main
    repoURL: https://github.com/mthang1801/argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true